var items = [
  {
    brand: "Tommy Hilfiger",
    type: "T-Shirt",
    price: "39.90",
    image: require("./assets/tommy1.png"),
    sizes: ["XS", "S", "M"],
    new: "new",
  },
  {
    brand: "Ralph Lauren",
    type: "T-Shirt",
    price: "64.00",
    sizes: ["S", "M"],
    image: require("./assets/ralph2.png"),
    new: "new",
  },
  {
    brand: "Lacoste",
    type: "T-Shirt",
    price: "50.00",
    sizes: ["S", "M", "XL"],
    image: require("./assets/lac.png"),
    new: "new",
  },
  {
    brand: "Gucci",
    type: "T-Shirt",
    price: "450.00",
    sizes: ["M"],
    image: require("./assets/gucci.png"),
  },
  {
    brand: "Versace",
    type: "T-Shirt",
    price: "200.00",
    sizes: ["L", "XL"],
    image: require("./assets/versace.png"),
    new: "new",
  },
  {
    brand: "Burberry",
    type: "T-Shirt",
    price: "230.09",
    sizes: ["S", "L"],
    image: require("./assets/burberry.png"),
    new: "new",
  },
  {
    brand: "Guess",
    type: "T-Shirt",
    price: "20.90",
    sizes: ["M"],
    image: require("./assets/guess.png"),
  },
  {
    brand: "Hugo Boss",
    type: "Polo T-Shirt",
    price: "50.99",
    sizes: ["L"],
    image: require("./assets/hugo.png"),
  },
  {
    brand: "Diesel",
    type: "T-Shirt",
    price: " 65.90",
    sizes: ["M", "L", "XL"],
    image: require("./assets/diesel.png"),
  },
  {
    brand: "Dolce & Gabanna",
    type: "Polo T-Shirt",
    price: "230.90",
    sizes: ["L"],
    image: require("./assets/dolce.png"),
  },
  {
    brand: "Prada",
    type: "T-Shirt",
    price: " 450.90",
    sizes: ["S", "M", "L", "XL"],
    image: require("./assets/prada.png"),
    new: "new",
  },
  {
    brand: "U.S Polo Assn.",
    type: "Polo T-Shirt",
    price: " 55.99",
    sizes: ["XS", "S", "M", "L"],
    image: require("./assets/usPolo.png"),
    new: "new",
  },
  {
    brand: "Emporio Armani",
    type: "T-Shirt",
    price: " 80.99",
    sizes: ["XS", "S", "L"],
    image: require("./assets/armani1.png"),
    new: "new",
  },
  {
    brand: "Emporio Armani",
    type: "T-Shirt",
    price: " 100.50",
    sizes: ["XS", "S", "M", "L", "XL"],
    image: require("./assets/armani2.png"),
  },
  {
    brand: "Emporio Armani",
    type: "T-Shirt",
    price: " 87.50",
    sizes: ["XS", "S", "M", "L"],
    image: require("./assets/armani3.png"),
    new: "new",
  },
  {
    brand: "Fendi",
    type: "T-Shirt",
    price: " 800.50",
    sizes: ["XS", "S", "M", "L"],
    image: require("./assets/fendi1.png"),
  },
  {
    brand: "Fendi",
    type: "T-Shirt",
    price: " 620.00",
    sizes: ["XS", "S", "M", "L"],
    image: require("./assets/fendi2.png"),
  },
  {
    brand: "Fred Perry",
    type: "Polo T-Shirt",
    price: "75.00",
    sizes: ["XS", "S", "M", "L"],
    image: require("./assets/fred1.png"),
    new: "new",
  },
  {
    brand: "Fred Perry",
    type: "Polo T-Shirt",
    price: " 90.00",
    sizes: ["XS", "S", "M", "L"],
    image: require("./assets/pred2.png"),
    new: "new",
  },
];

export default items;
